### ISSUE TITLE
質問：Presenter/PresenterAction/PresenterDelegateの

### ISSUE THREAD

**Issue by dchssk** [ykmt/ios-viper-sample#9]

**Comment by dchssk** [comment]
すみません、質問です（Issueで質問はマナー違反ではあるので、駄目でしたら今後はMessengerで。。）

[App|Greeting]Presenterと[App|Greeting]PresenterActionの使い分けの意図を知りたいです。

PresenterActionはViewからイベント伝達、PresenterDelegateはViewへのイベント伝達と認識しています。
そこで気になったのが、「どこでBehaviorを叩くべきか」
AppではAppPresenterが、GreetingではGreetingPresenterView[Action|Delegate]が、Behaviorを叩いています。

これはどこで叩いても良い、と考えてよいでしょうか

**Comment by ykmt** [comment]
Presenterは、Viewから発生するイベント全般とViewの更新を担当します。

ViewActionは、ボタンタップのアクション、他画面への画面遷移のトリガーを担当します。

ViewDelegateは、viewDidLoadなどのDelegateプロトコルの実装を担当します。

ViewAction、ViewDelegateは、Presenterの一部です。従って、PresenterとInteractorを参照します。また、Routerへもアクセスできます。

Behaviorですが、PresenterからView方向に向かうプロトコルで、Viewの画面更新に使用します。従って、ViewControllerはBehaviorプロトコルを適用し、Presenterから画面更新できるようにします。

Behaviorは、Presenterからであれば自由に呼んで良いと思います。

このような説明でよろしいでしょうか。

**Comment by dchssk** [comment]
ありがとうございます
